# syntax=docker/dockerfile:1.6
# Build stage

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

#Copy project file for cache restore
COPY auth_service.csproj ./
RUN dotnet restore ./auth_service.csproj


#Copy the source code
COPY . .

#Build + publish
RUN dotnet publish ./auth_service.csproj \
    -c Release \
    -o /app/publish \
    --no-restore \
    /p:UseAppHost=false

#Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

#Install curl for health checks
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

#COPY published output from build stage
COPY --from=build /app/publish ./

# Create non-root user (fixed UID/GID)
RUN groupadd -r appuser --gid 10001 \
    && useradd -r -g appuser --uid 10001 appuser \
    && chown -R appuser:appuser /app

USER appuser

EXPOSE 8080
ENV ASPNETCORE_URLS=http://0.0.0.0:8080\
     ASPNETCORE_ENVIRONMENT=Production\
     DOTNET_EnableDiagnostics=0


# Healthcheck 
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD curl -fsS http://127.0.0.1:8080/health || exit 1

ENTRYPOINT ["dotnet", "auth_service.dll"]
